### PR TITLE
Fixed parsing of llvm-config.h

### PR DESCRIPTION
**Pull request by yglukhov**
Current llvm-config.h contains the following string

``` c
#define LLVM_CONFIG_H
```

which causes range error with current way of parsing.

### CODE REVIEW

**Comment by jkm** [comment]
Against which version of LLVM are you testing?

**Comment by yglukhov** [comment]
Git master.
https://github.com/llvm-mirror/llvm/blob/master/include/llvm/Config/config.h.in

**Comment by jkm** [comment]
Do you happen to know since which release the change is needed? I need to put to the right branch.

**Comment by yglukhov** [comment]
Seems like the blame points to here: https://github.com/llvm-mirror/llvm/commit/d442d2846a00c0ac2f031deba06b7e0d003f14ad. I'm not sure what's the release though.

**Comment by jkm** [comment]
This is quite old. I wonder why this issue didn't pop up earlier. I will look into it.
I hope there is no hurry because you already fixed the problem yourself.

**Comment by yglukhov** [comment]
Sure, take your time.

**Pull request closed without merging**
